ignoredBuiltDependencies:
  - '@firebase/util'
  - '@scarf/scarf'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - core-js-pure
  - esbuild
  - protobufjs
  - sharp
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver
